name: Build and publish Python to PyPI

on: push

jobs:
  build-n-publish:
    name: Build and publish Python to PyPI
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: build
        run: |
          python -m pip install -U pip build twine
          python -m build --sdist --wheel --outdir dist/ .
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
